name: Triggered Workflow

on:
  push:
    branches:
      - main

concurrency:
  group: gopal-deployment-group
  cancel-in-progress: false

jobs:
  build-and-deploy-code:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout GoPalUI Repo repository
        uses: actions/checkout@v2
        with:
          repository: congpham234/GoPalApiModel
          ref: main

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Install dependencies
        run: npm install -g openapi-typescript-codegen

      - name: Link command
        run: npm link

      - name: Test Models generation
        run: generate-api-models